export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
export const MODAL_SET_VIDEO = 'MODAL_SET_VIDEO';

export const REQUEST_MOVIES_PENDING = 'REQUEST_MOVIES_PENDING';
export const REQUEST_MOVIES_SUCCESS = 'REQUEST_MOVIES_SUCCESS';
export const REQUEST_MOVIES_FAILED = 'REQUEST_MOVIES_FAILED';
